"""
probability_calibration.py -- Runtime fair-value probability calibration.

Loads calibration artifacts generated by scripts/analysis/calibrate_signal_probabilities.py
and applies either Platt scaling or isotonic mapping to raw model probabilities.
"""

from __future__ import annotations

import bisect
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

from model_families import SCORE_EVENT_TRANSITION


def _clamp_prob(p: float) -> float:
    return min(max(float(p), 1e-8), 1.0 - 1e-8)


def _stable_sigmoid(x: float) -> float:
    if x >= 0:
        z = math.exp(-x)
        return 1.0 / (1.0 + z)
    z = math.exp(x)
    return z / (1.0 + z)


def _logit(p: float) -> float:
    cp = _clamp_prob(p)
    return math.log(cp / (1.0 - cp))


def _line_key(line: Any) -> str:
    """Canonicalize a line value into the string key used in the
    calibration artifact's per-line block. Matches the builder's keying
    (samples store ``str(row["line"])``). Accepts numerics ("7.5") and
    strings ("7.5"). Returns the input stringified; callers should
    ensure non-canonical forms (e.g. trailing zeros) are normalized
    upstream if they cause mismatches."""
    return str(line)


@dataclass
class ProbabilityCalibrator:
    method: str
    params: Dict[str, Any]
    family_calibrators: Optional[Dict[str, "ProbabilityCalibrator"]] = None
    # Per-line stratified curves (2026-06-06). Map of line_key
    # (string, e.g. "5.5") -> calibrator instance. Populated when the
    # family payload's "lines" block is present. Runtime tries this
    # map first; falls back to the family-pooled curve (self) when
    # the line key isn't present or absent entirely.
    line_calibrators: Optional[Dict[str, "ProbabilityCalibrator"]] = None
    default_family: str = SCORE_EVENT_TRANSITION
    family_mode: str = "single"

    @classmethod
    def from_path(cls, path: Path | str) -> "ProbabilityCalibrator":
        p = Path(path)
        with open(p, encoding="utf-8") as f:
            payload = json.load(f)
        return cls.from_payload(payload)

    @classmethod
    def from_payload(cls, payload: Dict[str, Any]) -> "ProbabilityCalibrator":
        families = payload.get("families") if isinstance(payload, dict) else None
        if isinstance(families, dict) and families:
            default_family = str(payload.get("default_family") or SCORE_EVENT_TRANSITION)
            family_calibrators: Dict[str, ProbabilityCalibrator] = {}
            for family, family_payload in families.items():
                if isinstance(family_payload, dict):
                    family_calibrators[str(family)] = cls._from_single_payload(family_payload)
            default = (
                family_calibrators.get(default_family)
                or family_calibrators.get(SCORE_EVENT_TRANSITION)
                or next(iter(family_calibrators.values()))
            )
            return cls(
                method=default.method,
                params=dict(default.params),
                family_calibrators=family_calibrators,
                line_calibrators=default.line_calibrators,
                default_family=default_family,
                family_mode="separate",
            )

        return cls._from_single_payload(payload)

    @classmethod
    def _from_single_payload(cls, payload: Dict[str, Any]) -> "ProbabilityCalibrator":
        selected = str(payload.get("selected_method") or "identity").strip().lower()
        methods = payload.get("methods", {}) if isinstance(payload, dict) else {}
        selected_payload = methods.get(selected, {}) if isinstance(methods, dict) else {}
        params = selected_payload.get("params", {}) if isinstance(selected_payload, dict) else {}
        data = payload.get("data", {}) if isinstance(payload, dict) else {}
        model_family = str(data.get("model_family") or payload.get("default_family") or SCORE_EVENT_TRANSITION)
        if selected not in {"platt", "isotonic"}:
            selected = "identity"
            params = {}

        # Per-line stratification (2026-06-06). The "lines" block, when
        # present, holds a {line_key: per_line_payload} map where each
        # per-line payload mirrors the single-family schema (selected_method
        # + methods). Absent block / absent line falls back to the
        # family-pooled curve at call time.
        line_calibrators: Optional[Dict[str, ProbabilityCalibrator]] = None
        lines_block = payload.get("lines") if isinstance(payload, dict) else None
        if isinstance(lines_block, dict) and lines_block:
            line_calibrators = {}
            for line_key, line_payload in lines_block.items():
                if isinstance(line_payload, dict):
                    line_calibrators[str(line_key)] = cls._from_single_payload(line_payload)

        return cls(
            method=selected,
            params=dict(params),
            line_calibrators=line_calibrators,
            default_family=model_family,
            family_mode=str(payload.get("family_mode") or "single"),
        )

    def method_for_family(self, model_family: Optional[str] = None) -> str:
        if not self.family_calibrators:
            return self.method if self.has_family(model_family) else "identity"
        cal = self._resolve_family_calibrator(model_family, allow_fallback=False)
        return cal.method if cal is not None else "identity"

    def has_family(self, model_family: Optional[str] = None) -> bool:
        """Return whether a family-specific artifact exists for model_family."""
        if not self.family_calibrators:
            family = str(model_family or self.default_family or "").strip()
            return family == str(self.default_family or "").strip()
        family = str(model_family or self.default_family or "").strip()
        return family in self.family_calibrators

    def has_line_curve(
        self,
        model_family: Optional[str] = None,
        line: Optional[Any] = None,
    ) -> bool:
        """Return True iff a per-line curve is available for the
        requested (model_family, line). False means the family-pooled
        curve will be used."""
        if line is None:
            return False
        family_cal = self
        if self.family_calibrators:
            family_cal = self._resolve_family_calibrator(
                model_family, allow_fallback=False,
            )
            if family_cal is None:
                return False
        line_calibrators = getattr(family_cal, "line_calibrators", None)
        if not line_calibrators:
            return False
        return _line_key(line) in line_calibrators

    def _resolve_family_calibrator(
        self,
        model_family: Optional[str] = None,
        *,
        allow_fallback: bool,
    ) -> Optional["ProbabilityCalibrator"]:
        if not self.family_calibrators:
            return self
        family = str(model_family or self.default_family or "").strip()
        cal = self.family_calibrators.get(family)
        if cal is not None or not allow_fallback:
            return cal
        return (
            self.family_calibrators.get(self.default_family)
            or self.family_calibrators.get(SCORE_EVENT_TRANSITION)
        )

    def calibrate(
        self,
        prob: float,
        model_family: Optional[str] = None,
        *,
        line: Optional[Any] = None,
        allow_family_fallback: bool = True,
    ) -> float:
        if self.family_calibrators:
            cal = self._resolve_family_calibrator(
                model_family,
                allow_fallback=allow_family_fallback,
            )
            if cal is not None:
                return cal.calibrate(prob, line=line)
            return _clamp_prob(prob)

        # Per-line override (2026-06-06): try the per-line curve first,
        # silently fall through to the family-pooled curve when this
        # (family, line) doesn't have its own fit. Strictly additive
        # behavior: lines without per-line curves are calibrated
        # exactly as they were before this change.
        if line is not None and self.line_calibrators:
            line_cal = self.line_calibrators.get(_line_key(line))
            if line_cal is not None:
                return line_cal.calibrate(prob)

        raw = _clamp_prob(prob)
        if self.method == "platt":
            a = float(self.params.get("a", 1.0))
            b = float(self.params.get("b", 0.0))
            return _clamp_prob(_stable_sigmoid(a * _logit(raw) + b))

        if self.method == "isotonic":
            xs = [float(x) for x in self.params.get("x", [])]
            ys = [float(y) for y in self.params.get("y", [])]
            if len(xs) < 2 or len(xs) != len(ys):
                return raw
            if raw <= xs[0]:
                return _clamp_prob(ys[0])
            if raw >= xs[-1]:
                return _clamp_prob(ys[-1])
            idx = bisect.bisect_right(xs, raw)
            left = max(0, idx - 1)
            right = min(len(xs) - 1, idx)
            x0, x1 = xs[left], xs[right]
            y0, y1 = ys[left], ys[right]
            if x1 <= x0:
                return _clamp_prob(y0)
            t = (raw - x0) / (x1 - x0)
            return _clamp_prob(y0 + (y1 - y0) * t)

        return raw
