"""Column-list constants for the calibration-opportunity training
table. Extracted from build_calibration_opportunity_training_table.py
on 2026-05-25 as part of Tier 2 — pure data, no logic, just made
the orchestrator ~270 lines fatter than it needed to be.

Public surface: IDENTITY_COLUMNS, MARKET_COMPLEMENT_COLUMNS,
INFERENCE_PANEL_COLUMNS, MODEL_FEATURE_COLUMNS (plus any other
constants in the original block).
"""
from __future__ import annotations

from scripts.trading.scoring_path_features import (
    SCORING_PATH_FIELD_KEYS,
    SCORING_PATH_MODEL_FIELD_KEYS,
)
from scripts.trading.stage1_support import (
    STAGE1_SUPPORT_SUFFIXES,
    stage1_support_field_names,
)
from scripts.trading.weather_client import (
    WEATHER_FEATURE_FIELD_KEYS,
    WEATHER_MODEL_FEATURE_FIELD_KEYS,
)


IDENTITY_COLUMNS = [
    "schema_version",
    "mode",
    "session_date",
    "candidate_id",
    "outcome_join_key",
    "ts",
    "recorded_at",
    "signal_ts_epoch",
    "game_pk",
    "away_abbrev",
    "home_abbrev",
    "line",
    "side",
    "signal_model_family",
    "state_value_strategy",
    "decision",
    "decision_reason",
    "gate_policy_version",
    "calibration_repeat_policy",
    "calibration_repeat_group_key",
    "calibration_repeat_group_size",
    "calibration_repeat_group_index",
    "calibration_row_weight",
]

MARKET_COMPLEMENT_COLUMNS = [
    "over_token_id",
    "under_token_id",
    "over_best_bid",
    "over_best_ask",
    "over_mid",
    "over_spread",
    "over_ltp",
    "over_book_source",
    "decision_mid",
    "under_pair_available",
    "under_best_bid",
    "under_best_ask",
    "under_mid",
    "under_spread",
    "under_ltp",
    "under_book_source",
    "over_under_ask_sum",
    "over_under_bid_sum",
    "over_under_mid_sum",
    "over_mid_no_vig",
    "under_mid_no_vig",
    "decision_market_mid_no_vig",
]

INFERENCE_PANEL_COLUMNS = [
    "inference_panel_runs_considered",
    "inference_panel_selected_rule",
    "inference_panel_selected_runs",
    *[
        f"inference_run{runs}_{suffix}"
        for runs in (1, 2, 3)
        for suffix in (
            "selected",
            "away_score",
            "home_score",
            "total",
            "base_poisson",
            "base_empirical",
            "poisson_minus_empirical",
            "distance_to_ask",
            "empirical_distance_to_ask",
            "n",
            "n_samples",
            "effective_n",
            *(f"support_{suffix}" for suffix in STAGE1_SUPPORT_SUFFIXES),
            "fallback_level",
            "fallback_label",
            "cell_key",
            "line_fallback_mode",
            "line_source_key",
            "empirical_line_fallback_mode",
            "empirical_line_source_key",
        )
    ],
]

SELECTED_INFERRED_STATE_COLUMNS = [
    "inferred_state_base_poisson",
    "inferred_state_base_empirical",
    "inferred_state_poisson_minus_empirical",
    "inferred_state_empirical_edge",
    "inferred_state_n",
    "inferred_state_n_samples",
    "inferred_state_weighted_n",
    "inferred_state_effective_n",
    *stage1_support_field_names("inferred_state"),
    "inferred_state_fallback_level",
    "inferred_state_fallback_label",
    "inferred_state_cell_key",
    "inferred_state_line_key_poisson",
    "inferred_state_line_key_empirical",
    "inferred_state_line_fallback_mode",
    "inferred_state_empirical_line_fallback_mode",
    "inferred_state_empirical_line_source_key",
    "inferred_state_empirical_line_source_key_low",
    "inferred_state_empirical_line_source_key_high",
    "inferred_state_used_fallback",
    "inferred_state_base_source",
]

SELECTED_INFERRED_STATE_CORE_COLUMNS = [
    "inferred_state_base_poisson",
    "inferred_state_base_empirical",
    "inferred_state_poisson_minus_empirical",
    "inferred_state_n",
    "inferred_state_n_samples",
    "inferred_state_effective_n_proxy",
    "inferred_state_stage1_trust_weight",
    "inferred_state_fallback_level",
]

DECISION_TIME_AUDIT_COLUMNS = [
    "inning",
    "inning_state",
    "outs",
    "runners_on",
    "away_score_before",
    "home_score_before",
    "current_total",
    "home_leading_late",
    "batting_team_is_home",
    "bottom9_available_if_needed",
    "expected_remaining_half_innings",
    "expected_remaining_pa_bucket",
    "home_skip_bottom9_risk",
    *SCORING_PATH_FIELD_KEYS,
    *WEATHER_FEATURE_FIELD_KEYS,
    *MARKET_COMPLEMENT_COLUMNS,
    "runs_needed",
    "lead_abs",
    "inferred_runs",
    "decision_ask",
    "best_bid",
    "spread",
    "ask_bucket",
    "edge_bucket",
    "runs_needed_bucket",
    "phantom_risk_band",
    "fair_value",
    "fair_value_raw",
    "fair_value_calibrated",
    "base_fair_value",
    *SELECTED_INFERRED_STATE_COLUMNS,
    "stage2_run_env_delta",
    "stage2_weather_source",
    "stage2_weather_model_usable",
    "team_offense_delta",
    "edge",
    "min_edge_effective",
    "model_market_logit_residual",
    "raw_model_market_logit_residual",
    "current_state_market_logit_residual",
    "after_event_market_logit_residual",
    "empirical_state_market_logit_residual",
    "model_market_mid_no_vig_logit_residual",
    "empirical_state_mid_no_vig_logit_residual",
    *INFERENCE_PANEL_COLUMNS,
    "current_state_value_base_poisson",
    "current_state_value_base_empirical",
    "current_state_value_line_key_poisson",
    "current_state_value_line_key_empirical",
    "current_state_value_used_fallback",
    "current_state_value_state_fallback_level",
    "current_state_value_state_fallback_label",
    "current_state_value_state_cell_key",
    "current_state_value_line_fallback_mode",
    "current_state_value_line_source_key",
    "current_state_value_empirical_line_fallback_mode",
    "current_state_value_empirical_line_source_key",
    *stage1_support_field_names("current_state_value"),
    "current_state_value_fv_raw",
    "current_state_value_stage2_run_env_delta",
    "current_state_value_team_offense_delta",
    "current_state_value_edge",
    "current_state_value_empirical_edge",
    "current_state_value_away_score",
    "current_state_value_home_score",
    "current_state_value_total",
    "shadow_fv_current_state",
    "shadow_fv_after_inferred_score",
    "shadow_fv_inferred_lift",
    "shadow_no_event_edge",
    "shadow_after_event_edge",
    "shadow_p_score_event_proxy",
    "shadow_phantom_risk_score",
    "shadow_phantom_risk_band",
    "shadow_risk_tags",
    "shadow_low_ask_high_edge",
    "shadow_runs_needed_exact_3p5",
    "shadow_current_state_edge_bucket",
    "shadow_phantom_risk_bucket",
    "shadow_current_phantom_combo_bucket",
    "shadow_inning_bucket",
    "shadow_inning_runs_needed_bucket",
    "shadow_bottom9_home_lead_context",
    "shadow_home_skip_bottom9_risk_bucket",
    "shadow_post_tr20_extreme_020_pass",
    "shadow_post_tr20_ask_ramp_v2_pass",
    "shadow_post_tr20_gate6_relax_enforce_pass",
    "shadow_post_tr20_combined_pass",
    "score_segment_key",
    "score_segment_age_secs",
    "score_segment_drawdown",
    "shadow_no_score_drift_trigger",
    "posted_limit",
    "hypothetical_limit_price",
    "execution_ask",
    "execution_bid",
    "execution_policy_current_limit_price",
    "execution_policy_current_limit_ev_if_filled_per_share",
    "execution_policy_limit_plus_1c_price",
    "execution_policy_limit_plus_1c_ev_if_filled_per_share",
    "execution_policy_limit_plus_2c_price",
    "execution_policy_limit_plus_2c_ev_if_filled_per_share",
    "execution_policy_taker_like_price",
    "execution_policy_taker_like_ev_if_filled_per_share",
]

SCORE_CONFIRMATION_COLUMNS = [
    "score_confirmation_available",
    "score_confirmation_status",
    "score_confirmation_latency_secs",
    "observed_away_score",
    "observed_home_score",
    "observed_total",
    "score_delta_away",
    "score_delta_home",
    "score_delta_total",
    "score_confirmed_within_10s",
    "score_confirmed_within_30s",
    "score_confirmed_within_60s",
]

LABEL_COLUMNS = [
    "split",
    "split_date_rank",
    "label_final_available",
    "label_score_confirmation_available",
    "final_away",
    "final_home",
    "final_total",
    "target_trade",
    "target_over_win",
    "target_taker_profit_units",
    "target_limit_profit_units",
    "target_score_changed_any",
    "target_score_confirmed_10s",
    "target_score_confirmed_30s",
    "target_score_confirmed_60s",
    "target_no_score_change_60s",
    "target_phantom_no_score_60s",
]

_WEATHER_AUDIT_FIELD_SET = set(WEATHER_FEATURE_FIELD_KEYS)
_SCORING_PATH_NON_MODEL_FIELD_SET = set(SCORING_PATH_FIELD_KEYS) - set(SCORING_PATH_MODEL_FIELD_KEYS)

MODEL_FEATURE_COLUMNS = [
    c for c in DECISION_TIME_AUDIT_COLUMNS
    if c not in _WEATHER_AUDIT_FIELD_SET and c not in _SCORING_PATH_NON_MODEL_FIELD_SET
] + list(WEATHER_MODEL_FEATURE_FIELD_KEYS)


