#!/usr/bin/env python3
"""dump_refresh_steps.py -- print the canonical daily-refresh step list.

Single source of truth for "what does run_daily_refresh.py actually do?".
Reads the live step list from `build_refresh_steps()` with a default
RefreshConfig and prints it as Markdown so docs (README, MASTER_CONTEXT,
ROADMAP, AGENT_CONTEXT.md files) can paste the output instead of
hand-maintaining a list that drifts.

Usage:
    python scripts/analysis/dump_refresh_steps.py
    python scripts/analysis/dump_refresh_steps.py --format markdown  # default
    python scripts/analysis/dump_refresh_steps.py --format names     # one name per line
    python scripts/analysis/dump_refresh_steps.py --format count     # just the integer

The output is stable as long as `build_refresh_steps` is stable; a
diff-against-doc check in CI would catch drift.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parents[2]
ANALYSIS_DIR = PROJECT_DIR / "scripts" / "analysis"

if str(ANALYSIS_DIR) not in sys.path:
    sys.path.insert(0, str(ANALYSIS_DIR))

from run_daily_refresh import RefreshConfig, build_refresh_steps  # noqa: E402


def _default_active_date() -> str:
    # Use a stable placeholder so output doesn't churn day-over-day in docs.
    return "2026-05-25"


def _build_default_steps():
    # We pass non-empty `session_dates` + `max_date` so the FULL
    # base pipeline materializes (settlement_truth, per-date daily-review,
    # walk-forwards, certification, etc. all gate on `max_date` being set).
    # Two synthetic session dates are enough to surface the conditional
    # branches without dragging in real ledger data.
    active = _default_active_date()
    config = RefreshConfig(active_date=active)
    # Use ONE synthetic session date so the per-date
    # `daily_human_review:<date>` step appears exactly once -- enough to
    # show the conditional fires, without inflating the step count by N
    # for every fake date.
    fake_session_dates = ["2026-05-24"]
    return build_refresh_steps(
        config,
        session_dates=fake_session_dates,
        max_date="2026-05-24",
    )


def render_markdown(steps) -> str:
    lines = [
        f"<!-- AUTO-GENERATED by scripts/analysis/dump_refresh_steps.py from",
        f"     build_refresh_steps() in run_daily_refresh.py. Re-run when",
        f"     the step list changes; do not hand-edit. -->",
        f"",
        f"**Daily refresh pipeline: {len(steps)} steps** (base; per-date",
        f"`daily_human_review:<date>` steps are appended for stale sessions)",
        f"",
        f"| # | Step | Kind | Description |",
        f"|--:|---|---|---|",
    ]
    for i, step in enumerate(steps, 1):
        # Markdown-escape pipe chars in description and collapse whitespace.
        desc = " ".join((step.description or "").split())
        desc = desc.replace("|", "\\|")
        lines.append(f"| {i} | `{step.name}` | {step.kind} | {desc} |")
    return "\n".join(lines) + "\n"


def render_names(steps) -> str:
    return "\n".join(step.name for step in steps) + "\n"


def render_count(steps) -> str:
    return f"{len(steps)}\n"


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--format",
        choices=["markdown", "names", "count"],
        default="markdown",
    )
    args = parser.parse_args(argv)

    steps = _build_default_steps()
    if args.format == "markdown":
        sys.stdout.write(render_markdown(steps))
    elif args.format == "names":
        sys.stdout.write(render_names(steps))
    elif args.format == "count":
        sys.stdout.write(render_count(steps))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
